# Generated by Django 5.1.6 on 2025-06-02 14:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('isRemoved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.user')),
                ('teacherImageURL', models.CharField(max_length=255)),
                ('badge', models.CharField(max_length=20)),
                ('point', models.IntegerField()),
                ('allTimeTopOne', models.IntegerField()),
                ('allTimeTopThree', models.IntegerField()),
                ('summaryDone', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='isStaff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='isSuperUser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='lastLogin',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='noname', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('teacher', 'Teacher'), ('student', 'Student')], default='admin', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('quit', 'Quit')], default='active', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('link', models.CharField(max_length=100)),
                ('isRemoved', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('sessionCreated', 'Session Created'), ('sessionReminder', 'Session Reminder'), ('noSessionLeft', 'No Session Left'), ('addSessionRequest', 'Add Session Request'), ('issuePayment', 'Issue Payment'), ('incomingPayment', 'Incoming Payment'), ('paymentOverdue', 'Payment Overdue'), ('paymentConfirmed', 'Payment Confirmed'), ('paymentDeclined', 'Payment Declined'), ('certificateIssued', 'Certificate Issued'), ('certificateConfirmed', 'Certificate Confirmed'), ('certificateDeclined', 'Certificate Declined'), ('newCertificate', 'New Certificate'), ('remindSummary', 'Remind Summary'), ('remindCertificate', 'Remind Certificate')], max_length=30)),
                ('message', models.TextField()),
                ('isRead', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.user')),
                ('studentImageURL', models.CharField(max_length=255)),
                ('paymentPending', models.IntegerField()),
                ('remainingSession', models.IntegerField()),
                ('sessionDone', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionAmount', models.IntegerField()),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('chargeAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.IntegerField(choices=[(0, 'Requested'), (1, 'Issued'), (2, 'Pending Confirmation'), (3, 'Paid'), (4, 'Overdue')])),
                ('paymentCreated', models.BooleanField(default=False)),
                ('dueDate', models.DateField()),
                ('paidConfirmedDate', models.DateField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student')),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('mastery', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')])),
                ('attitude', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')])),
                ('improvement', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')])),
                ('summary', models.TextField()),
                ('notes', models.CharField(max_length=255)),
                ('imageURL', models.CharField(max_length=255)),
                ('certificateReminder', models.BooleanField(default=False)),
                ('certificateCreated', models.BooleanField(default=False)),
                ('summaryCreated', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.material')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('mastery', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')])),
                ('attitude', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')])),
                ('improvement', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')])),
                ('description', models.TextField()),
                ('projectFile', models.CharField(max_length=255)),
                ('projectLink', models.CharField(max_length=255)),
                ('signatureLogo', models.CharField(max_length=255)),
                ('certificateImage', models.CharField(max_length=255)),
                ('isAccepted', models.BooleanField(default=False)),
                ('adminNotes', models.CharField(max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.material')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student')),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.summary')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekStart', models.DateField()),
                ('weekEnd', models.DateField()),
                ('rank', models.IntegerField()),
                ('basePoints', models.IntegerField()),
                ('bonusPoints', models.IntegerField()),
                ('totalPoints', models.IntegerField()),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.teacher')),
            ],
            options={
                'unique_together': {('teacher', 'weekStart')},
            },
        ),
    ]
