# Generated by Django 5.1.6 on 2025-06-02 17:35

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0002_course_session_teacher_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='noname', error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='certificate',
            name='adminNotes',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='attitude',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], default=1),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificateImage',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='improvement',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], default=1),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='mastery',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], default=1),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='projectFile',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='projectLink',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='signatureLogo',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='basePoints',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='bonusPoints',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='totalPoints',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='material',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='material',
            name='link',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='material',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='payment',
            name='chargeAmount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='dueDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='sessionAmount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.IntegerField(choices=[(0, 'Requested'), (1, 'Issued'), (2, 'Pending Confirmation'), (3, 'Paid'), (4, 'Overdue')], default=0),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='paymentPending',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='remainingSession',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='sessionDone',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentImageURL',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='summary',
            name='attitude',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], default=1),
        ),
        migrations.AlterField(
            model_name='summary',
            name='imageURL',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='summary',
            name='improvement',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], default=1),
        ),
        migrations.AlterField(
            model_name='summary',
            name='mastery',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], default=1),
        ),
        migrations.AlterField(
            model_name='summary',
            name='notes',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='summary',
            name='summary',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='allTimeTopOne',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='allTimeTopThree',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='badge',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='point',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='summaryDone',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacherImageURL',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=6),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastLogin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('teacher', 'Teacher'), ('student', 'Student')], default='student', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('quit', 'Quit')], default='active', max_length=10),
        ),
    ]
