# Generated by Django 5.1.6 on 2025-06-03 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='isStaff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='isSuperUser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lastLogin',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
