# Generated by Django 5.1.6 on 2025-06-03 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_createdat_user_created_at_remove_user_isstaff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='studentImageURL',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='teacherImageURL',
        ),
        migrations.AddField(
            model_name='student',
            name='studentImage',
            field=models.ImageField(default='default_student.jpg', upload_to='student_pics/'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacherImage',
            field=models.ImageField(default='default_teacher.jpg', upload_to='profile_pics/'),
        ),
    ]
