# Generated by Django 5.1.6 on 2025-06-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_student_studentimageurl_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summary',
            name='imageURL',
        ),
        migrations.AddField(
            model_name='payment',
            name='paymentImage',
            field=models.ImageField(blank=True, default='payment_proofs/default.jpg', null=True, upload_to='payment_proofs/'),
        ),
        migrations.AddField(
            model_name='summary',
            name='summaryImage',
            field=models.ImageField(default='summary_images/default.jpg', upload_to='summary_images/'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificateImage',
            field=models.ImageField(default='certificate_images/default.jpg', upload_to='certificate_images/'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='projectFile',
            field=models.FileField(default='project_files/default.zip', upload_to='project_files/'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='signatureLogo',
            field=models.ImageField(default='signatures/default.jpg', upload_to='signatures/'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday')], default='Monday', max_length=20),
        ),
    ]
