# Generated by Django 5.1.6 on 2025-06-04 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_summary_imageurl_payment_paymentimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.CharField(default='No grade', max_length=100),
        ),
    ]
