# Generated by Django 5.1.6 on 2025-06-09 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_student_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='studentImage',
            field=models.ImageField(default='student_pics/default_students/default_student.png', upload_to='student_pics/'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='course',
            field=models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, to='core.course'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='material',
            field=models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, to='core.material'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='notes',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='summary',
            name='summary',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacherImage',
            field=models.ImageField(default='default_teacher.png', upload_to='profile_pics/'),
        ),
    ]
