# Generated by Django 5.1.6 on 2025-06-09 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_student_studentimage_alter_summary_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='teacher',
            field=models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, to='core.teacher'),
        ),
    ]
