# Generated by Django 5.1.6 on 2025-06-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_summary_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='notes',
            field=models.CharField(blank=True, default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='summary',
            name='summary',
            field=models.TextField(blank=True, default=' '),
        ),
    ]
